# Generated by Django 4.2.3 on 2023-08-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter name of category...', max_length=100),
        ),
    ]
